Repository cca-ffodregamdi/running-hi-frontend, pull requests merged in 2023-08, with the labels that each got.

#18 [Style] SVG 컴포넌트화, atoms 모두 구현
  src/component/UI/atoms/Button/confirmButton/confirmButton.svg
  src/component/UI/atoms/else/cursur/cursur.jsx
Labels: 🤍 Html & CSS, ➕ Feature

#14 [Bugfix] - {MAIN} 에러 수정
  src/App.js
Labels: ⚠️ BugFix

#30 [Feature] | DarkMode 구현 시작(ing-) , Style-components, react-router 세팅
  package-lock.json
  package.json
  src/App.js
  src/component/UI/Effect/useDarkMode/globalStyle.js
  src/component/UI/Effect/useDarkMode/toggle.jsx
  src/component/UI/Effect/useDarkMode/useDarkMode.jsx
  src/component/UI/atoms/Button/Btn-of-SVG/DaymodeBtn/DaymodeBtn .jsx
  src/component/pages/Log/FindIDPage/FindIDPage.jsx
  src/component/pages/Main/mainHomePage/mainHomePage.jsx
  src/component/pages/Post/comment/comment.jsx
  src/component/pages/Post/comment/commentList.jsx
  src/index.js
Labels: ⚙️Settings, ➕ Feature, 🌈 UI
